<a href="https://colab.research.google.com/github/Sammypacoo/Rosalind/blob/main/Projeto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import plotly.graph_objects as go

categories = ['GNOMAD', 'SABE']

fig = go.Figure()


fig.add_trace(go.Scatterpolar(
      r=[12.9, 9.09],
      theta=categories,
      fill='toself',
      name='APP'
))
fig.add_trace(go.Scatterpolar(
      r=[27.8, 19.3],
      theta=categories,
      fill='toself',
      name='MAPT'
))

fig.add_trace(go.Scatterpolar(
      r=[13,0],
      theta=categories,
      fill='toself',
      name='PSEN1'
))
fig.add_trace(go.Scatterpolar(
      r=[10.4,0],
      theta=categories,
      fill='toself',
      name='PSEN2'
))
fig.add_trace(go.Scatterpolar(
      r=[ 6.2,5],
      theta=categories,
      fill='toself',
      name='TREM2'
))


fig.update_layout(
  polar=dict(
    radialaxis=dict(
      visible=True,
      range=[0, 50]
    )),
  showlegend=True
)

fig.show()

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
from collections import defaultdict
import gzip
import pandas as pd
import re

#Funções do código

In [7]:
def Convert(tup, di):
    for a, b in tup:
        di.setdefault(a, []).append(b)
    return di
      
# Driver Code    
tups = [("akash", 10), ("gaurav", 12), ("anand", 14), 
     ("suraj", 20), ("akhil", 25), ("ashish", 30)]
dictionary = {}
print (Convert(tups, dictionary))

{'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}

In [8]:

variantes=pd.read_csv("/content/drive/MyDrive/Projeto/Projeto/Arquivos_do_projeto/app_gnomad.csv", sep=';')
variantes.columns



arq1=pd.read_csv("/content/drive/MyDrive/Projeto/Projeto/Arquivos_importantes_p_codigo/CCDS.current.txt" , sep='\t')


arq2=arquivo=pd.read_csv("/content/drive/MyDrive/Projeto/Projeto/Arquivos_importantes_p_codigo/CCDS2Sequence.current.txt" , sep='\t')


arq3=pd.read_csv("/content/drive/MyDrive/Projeto/Projeto/Arquivos_importantes_p_codigo/exon_seq1", header= None , sep='\t')
# criei uma tabela com os dados CCDS_protein_exons.current.faa"

df=pd.read_table("/content/drive/MyDrive/Projeto/Projeto/Arquivos_importantes_p_codigo/GRCh38_latest_genomic.gtf",header=None,skiprows=4)

In [9]:


def tab_final(gene):

    arq1.shape
    arq1.rename(columns={"ccds_id":"#ccds"}, inplace = True)
    arq1.columns
    app=arq1[arq1["gene"]==gene]
    app.shape
    app.columns
    app

    result = pd.merge(app, arq2, on="#ccds",how="left")
    result = result.drop_duplicates()
    result=result[result["source"]=="NCBI"]
    result=result[result["status_in_CCDS"]=="Accepted"]
    result
    return result

In [10]:
# Para cada posição do genomica, mostra tods os NM relacionados aquela posi genomica
def tab_teste1(final,x):
  x=int(x)

  # Fazer listas das extremidades do gene

  ext1=final.iloc[:,7].tolist()
  ext2=final.iloc[:,8].tolist()
  lista_fil1=[]
  for j in range (len(ext1)):
      x1=ext1[j]
      x1=int(x1)+1
      x2=ext2[j]
      x2=int(x2)+2
      r=range(x1,x2)

      if x in r:
          lista_fil1+=[1]
      else:
          lista_fil1+=[0]
  teste=final
  teste["filtro1"]=lista_fil1
  teste=teste[teste["filtro1"]==1]


  # Verificar em  quais nms aquela posi genômica está presente 
  tam1=teste.shape
  tam1=tam1[0]
  lista_fil2=[]
  for xl in range(tam1):
      f1=teste.iloc[xl,9]
      f1=str(f1)
      f1=re.findall(r'[0-9]+', f1)
      for xl1 in range (0,len(f1)-1,2):
          ini=f1[xl1]
          ini=int(ini)+1
          final=f1[xl1+1]
          final=int(final)+2
          r3=range(ini,final)
          if x in r3:
            lista_fil2+=[1] 
            break
          else:
            if xl1 == len(f1)-2:
                lista_fil2+=[0]
           

  teste["filtro2"]=lista_fil2
  teste1=teste[teste["filtro2"]==1]

     
  #teste1.rename(columns={5:"#ccds"}, inplace = True)
  return teste1

In [11]:
# final seria o teste1
def tab_exons_seq(final):
  taman=final.shape
  taman=taman[0]
  if taman >0:
    df=pd.DataFrame()  
    dic={}
    dic2={}
    g2=[]
    for i in range (taman):
      strand=final.iloc[i,6]
      dic={}
      bb=final.iloc[i,9]
      tf=bb.replace("[","")
      tf=tf.replace("]","")
      tf=tf.split(",")
      for i2 in range(len(tf)):    
        p=tf[i2]
        p=p.split("-")
        p=p[0]
        p=int(p)
        dic[tf[i2]]=p
      d_descending =sorted(dic.items(), key=lambda x: x[1], reverse=True)
      g1=dic.keys()
      g1=list(g1)
      dic2={}
      Convert(d_descending, dic2)
      g2=dic2.keys()
      g2=list(g2)
      g=final.iloc[i,4]
      if strand=="-":
        strand='-'
        y=arq3[arq3[0]==g]
        y["éxon"]=g2
      else:
        strand='+'
        y=arq3[arq3[0]==g]
        y["éxon"]=g1

      
      lin=y.shape
      lin=lin[0]
      list_strand=[]
      for it in range(lin):
          list_strand+=[strand]
      y["strand"]=list_strand
      df=pd.concat([df,y],axis=0)
  else:
     df=pd.DataFrame() 

  return df

In [12]:
def resul(teste1,df,x):
  x=int(x)
  taman=df.shape
  taman=taman[0]
  if taman >0:
    lis=df.iloc[:,0].unique()
    lis=lis.tolist()

    l1=[]
    #colocar o for
    for jkk in range(len(lis)):
      f=df[df[0]==lis[jkk]]
      ggp=f[4].tolist()
      listp=[]
      for j in range (len(ggp)):
        ggp1=len(ggp[j])
        listp+=[ggp1]
      f["tamanho"]=listp

      listp2=[0]
      valor=0
      for j1 in range (len(listp)-1):
        valor=valor + listp[j1]
        listp2+=[valor]
      f["Start_Value"]=listp2
      l=[]    
      for j2 in range (len(listp)):
        ran=f.iloc[j2,5]
        ran=ran.split("-")
        a1=int(ran[0])+1
        b1=int(ran[1])+2
        r=range(a1,b1)
        if x in r:
          l+=[1]
        else:
          l+=[0]

      f["filtro"]=l
      gg3=f[f["filtro"]==1]

      strand=gg3.iloc[0,6]
      ran=gg3.iloc[0,5]

      cc=ran.split("-")
      a1=int(cc[0])+1
      b1=int(cc[1])+1
      

      if strand=="-":
        d=b1-x       
        s=(d//3)+1
      else:
        a1=a1-1
        d=x-a1
        
        s=(d//3)
        

        

      s1=gg3.iloc[0,8]
      
      s,s1
      res=s+s1
      res
      l1+=[res]


    nm=teste1.iloc[:,14]
    nm=nm.tolist()

    gg4=pd.DataFrame(nm,columns=["Nm"])
    gg5=pd.DataFrame(l1,columns=["Pos"])
    gg6=pd.concat([gg4,gg5],axis=1)
    tamk=gg6.shape
    tamk=tamk[0]
    listaf=[]
    for ih in range (tamk):
      it=gg6.iloc[ih,:]
      it=it.tolist()
      listaf+=[it]
  else:
    listaf=[]
  return listaf

In [13]:
import re 

def sitios(X,gene):
    if len(X)>0:
      ptm=pd.read_csv("/content/drive/MyDrive/Projeto/Projeto/Arquivos_do_projeto/Arquivos_importantes/phosphositeplus_allptms_REFSEQ1", sep='\t')
      ptm.columns

      ptm=ptm[ptm["GENE"]==gene]
      ptm.dropna(subset = ["Refseq_semdigito"], inplace=True)
      nm_sitio=ptm["Refseq_semdigito"].tolist()
      tes=ptm["Refseq_semdigito"].unique()
      lista=[]
      for cd in range (len(nm_sitio)):
          x=nm_sitio[cd]
          x=str(x)
          x1=re.findall(r'\bNM_\w+',x)
          x1=x1[0]
          lista+=[x1]
      
      
      ptm["R"]=lista
      pos_sitio=ptm["SITE"].tolist()
      lista2=[]
      for cd1 in range (len(pos_sitio)):
          #print(cd1)
          x=pos_sitio[cd1]
          x=str(x)
          x1=re.findall(r'[0-9]+',x)
          x1=x1[0]
          x1=int(x1)
          #print(x1)
          lista2+=[x1]
      len(lista2)
      ptm["Posição"]=lista2
      s="n"
      lista4=[]
      for i in range (len(X)):
          nm=X[i][0]
          nm=re.findall(r'\bNM_\w+',nm)
          nm=nm[0]
          pos=X[i][1]
          pos=str(pos)
          pos=re.findall(r'[0-9]+', pos)
          pos=pos[0]
          pos=int(pos)
          
          A=pos+1
          a=pos-1
          lista1=[a,pos,A]
          t=-2  
          nm_sitio=ptm[ptm["R"]==nm]
      
          tam=nm_sitio.shape
          tam=tam[0]
          if tam!=0:
              #print("entrei")
                    
              for v in range (len(lista1)):
                  sitio_p=lista1[v]
                  #print(sitio_p)
                  t+=1
      
                  p_sitio=nm_sitio[nm_sitio["Posição"]==sitio_p]
                  #print(p_sitio)
      
                  tam1=p_sitio.shape
                  tam1=tam1[0]
                  if tam1!=0:
                      #print("entrei1")                
                      s="s"
                      tam3=p_sitio.shape
                      tam3=tam3[0]
                      lista3=[]
                      for k in range (tam3):
                          row=p_sitio.iloc[:,[0,1,12,13]]
                          row=row.iloc[k,:].tolist()
                          row+=[t]
                          
                          lista3+=[row]
                      lista4+=[lista3]
                    
                      break

    else : 
      s="n"
      lista4=[]                     
    return s, lista4

#total

In [ ]:
dic={"APP":"/content/drive/MyDrive/Projeto/Projeto/Arquivos_do_projeto/app_gnomad.csv",
     "MAPT":"/content/drive/MyDrive/Projeto/Projeto/MAPT_gnomad.csv",
     "PSEN1":"/content/drive/MyDrive/Projeto/Projeto/PSEN1_gnomad.csv",
     "PSEN2":"/content/drive/MyDrive/Projeto/Projeto/PSEN2_gnomad.csv",
     "TREM2":"/content/drive/MyDrive/Projeto/Projeto/TREM2_gnomad.csv"}
dic_re={}
df_resul_gnomad=pd.DataFrame(columns=["Gene","Gnomad Total","Gnomad_ptm","Gnomad_Porc"])


for chave in dic :
  if chave=="APP":
    variantes=pd.read_csv(dic[chave], sep=';')
  else:
    variantes=pd.read_csv(dic[chave], sep=',')
  gene=chave
  final=tab_final(gene)
  final
  variantes.head()
  variantes=variantes[variantes["VEP Annotation"]=="missense_variant"]
  variantes
  list_x=variantes["Position"].tolist()

  tk=[]
  tk1=[]
  tk2=[]
  for hgh in range(len(list_x)):
    print(hgh)  
    x=list_x[hgh]

    teste1=tab_teste1(final,x)
    teste1

    df=tab_exons_seq(teste1)
    #print(df)
    lista=resul(teste1,df,x)

    a,b=sitios(lista,gene)
    tk+=[a]
    tk1+=[b]
    tk2+=[lista]
  print(tk)
  variantes["PTM"]=tk
  variantes["PTM_INF"]=tk1
  variantes["Variantes"]=tk2
  variantes_gnomad_sabe=variantes
  variantes_sito=variantes[variantes["PTM"]=="s"]
  dic_re[chave]=variantes_sito
  X=len(variantes)
  X1=len(variantes_sito)
  X2=(X1*100)/X
  X,X1,X2
  lg=[chave,X,X1,X2]
  df_resul_gnomad.loc[len(df_resul_gnomad)] = lg
  df_resul_gnomad

In [15]:
  df_resul_gnomad

    Gene Gnomad Total Gnomad_ptm  Gnomad_Porc
0    APP          263         34    12.927757
1   MAPT          355         99    27.887324
2  PSEN1          138         18    13.043478
3  PSEN2          191         20    10.471204
4  TREM2          120          6     5.000000

In [21]:
dic_re

{'APP':      Chromosome  Position         rsIDs Reference Alternate          Source  \
 0            21  25881702   rs766455623         T         C  gnomAD Genomes
 1            21  25881705  rs1300518717         G         T  gnomAD Genomes
 3            21  25881734  rs1437503550         G         C  gnomAD Genomes
 29           21  25897632  rs1259157720         C         T  gnomAD Genomes
 30           21  25897641   rs200084346         T         A  gnomAD Genomes
 31           21  25897642    rs63750363         C         G  gnomAD Genomes
 33           21  25897649   rs200260102         G         A  gnomAD Genomes
 34           21  25897655   rs201104127         A         G  gnomAD Genomes
 35           21  25897659   rs770773038         T         C  gnomAD Genomes
 36           21  25897667           NaN         C         G  gnomAD Genomes
 37           21  25897668  rs1305531440         C         T  gnomAD Genomes
 54           21  25911849   rs201724379         T         C  gnomAD Genomes
 55           21  25911851   rs200088099         G         A  gnomAD Genomes
 56           21  25911855   rs140304729         C         T  gnomAD Genomes
 85           21  25954656           NaN         T         C  gnomAD Genomes
 102          21  25955728   rs201384815         T         G  gnomAD Genomes
 116          21  25975122   rs199549173         C         T  gnomAD Genomes
 117          21  25975123   rs200548072         G         A  gnomAD Genomes
 118          21  25975125   rs746164396         C         T  gnomAD Genomes
 119          21  25975126  rs1162419578         G         A  gnomAD Genomes
 120          21  25975129  rs1424012655         C         A  gnomAD Genomes
 124          21  25975203   rs749605439         A         G  gnomAD Genomes
 127          21  25975966  rs1418014426         C         A  gnomAD Genomes
 128          21  25975967   rs188433801         T         C  gnomAD Genomes
 138          21  25982424   rs752243493         G         A  gnomAD Genomes
 139          21  25982427  rs1322571887         T         C  gnomAD Genomes
 140          21  25982430   rs755703063         C         T  gnomAD Genomes
 142          21  25982462  rs1193124736         G         T  gnomAD Genomes
 143          21  25982472   rs748168213         T         C  gnomAD Genomes
 144          21  25997360   rs749453173         G         C  gnomAD Genomes
 145          21  25997360   rs749453173         G         A  gnomAD Genomes
 215          21  26051045   rs376138420         G         A  gnomAD Genomes
 221          21  26051070   rs145081708         A         G  gnomAD Genomes
 228          21  26051129   rs758637653         T         C  gnomAD Genomes

      Filters - exomes Filters - genomes         Transcript HGVS Consequence  \
 0                 NaN              PASS  ENST00000346798.8      p.Thr761Ala
 1                 NaN              PASS  ENST00000346798.8      p.Pro760Thr
 3                 NaN              PASS  ENST00000346798.8      p.Ser750Cys
 29                NaN              PASS  ENST00000346798.8      p.Val669Met
 30                NaN              PASS  ENST00000346798.8      p.Ile666Phe
 31                NaN              PASS  ENST00000346798.8      p.Glu665Asp
 33                NaN              PASS  ENST00000346798.8      p.Thr663Met
 34                NaN              PASS  ENST00000346798.8      p.Ile661Thr
 35                NaN              PASS  ENST00000346798.8      p.Asn660Asp
 36                NaN              PASS  ENST00000346798.8      p.Gly657Ala
 37                NaN              PASS  ENST00000346798.8      p.Gly657Arg
 54                NaN              PASS  ENST00000346798.8      p.Lys601Glu
 55                NaN              PASS  ENST00000346798.8      p.Thr600Met
 56                NaN              PASS  ENST00000346798.8      p.Glu599Lys
 85                NaN              PASS  ENST00000346798.8      p.Met541Val
 102               NaN              PASS  ENST00000346798.8      p.Lys496Gln
 116               NaN              PASS  ENST00000346798.8      p.Arg469His
 117               NaN              PASS  ENST00000346798.8      p.Arg469Cys
 118               NaN              PASS  ENST00000346798.8      p.Arg468His
 119               NaN              PASS  ENST00000346798.8      p.Arg468Cys
 120               NaN              PASS  ENST00000346798.8      p.Asp467Tyr
 124               NaN              PASS  ENST00000346798.8      p.Leu442Ser
 127               NaN              PASS  ENST00000346798.8      p.Lys429Asn
 128               NaN              PASS  ENST00000346798.8      p.Lys429Arg
 138               NaN              PASS  ENST00000346798.8      p.Pro382Ser
 139               NaN              PASS  ENST00000346798.8      p.Thr381Ala
 140               NaN              PASS  ENST00000346798.8      p.Glu380Lys
 142               NaN              PASS  ENST00000346798.8      p.Ala369Asp
 143               NaN              PASS  ENST00000346798.8      p.Thr366Ala
 144               NaN              PASS  ENST00000346798.8      p.Leu364Val
 145               NaN              PASS  ENST00000346798.8      p.Leu364Phe
 215               NaN              PASS  ENST00000346798.8      p.Ser206Leu
 221               NaN              PASS  ENST00000346798.8      p.Ser198Pro
 228               NaN              PASS  ENST00000346798.8      p.Lys178Arg

      ... Allele Number Ashkenazi Jewish Homozygote Count Ashkenazi Jewish  \
 0    ...                           3470                                 0
 1    ...                           3470                                 0
 3    ...                           3472                                 0
 29   ...                           3472                                 0
 30   ...                           3472                                 0
 31   ...                           3470                                 0
 33   ...                           3472                                 0
 34   ...                           3472                                 0
 35   ...                           3472                                 0
 36   ...                           3472                                 0
 37   ...                           3470                                 0
 54   ...                           3468                                 0
 55   ...                           3470                                 0
 56   ...                           3472                                 0
 85   ...                           3472                                 0
 102  ...                           3472                                 0
 116  ...                           3470                                 0
 117  ...                           3472                                 0
 118  ...                           3470                                 0
 119  ...                           3472                                 0
 120  ...                           3468                                 0
 124  ...                           3468                                 0
 127  ...                           3472                                 0
 128  ...                           3472                                 0
 138  ...                           3470                                 0
 139  ...                           3470                                 0
 140  ...                           3466                                 0
 142  ...                           3472                                 0
 143  ...                           3466                                 0
 144  ...                           3470                                 0
 145  ...                           3470                                 0
 215  ...                           3468                                 0
 221  ...                           3470                                 0
 228  ...                           3470                                 0

     Hemizygote Count Ashkenazi Jewish Allele Count European (non-Finnish)  \
 0                                   0                                   1
 1                                   0                                   0
 3                                   0                                   1
 29                                  0                                   2
 30                                  0                                   1
 31                                  0                                   1
 33                                  0                                   1
 34                                  0                                   1
 35                                  0                                   3
 36                                  0                                   1
 37                                  0                                   0
 54                                  0                                   1
 55                                  0                                   0
 56                                  0                                  79
 85                                  0                                   1
 102                                 0                                   1
 116                                 0                                   1
 117                                 0                                   2
 118                                 0                                   1
 119                                 0                                   0
 120                                 0                                   1
 124                                 0                                   1
 127                                 0                                   1
 128                                 0                                   0
 138                                 0                                   1
 139                                 0                                   1
 140                                 0                                   0
 142                                 0                                   1
 143                                 0                                   1
 144                                 0                                   0
 145                                 0                                   2
 215                                 0                                   1
 221                                 0                                   9
 228                                 0                                   0

      Allele Number European (non-Finnish)  \
 0                                   68006
 1                                   68028
 3                                   68032
 29                                  68030
 30                                  68026
 31                                  68024
 33                                  68012
 34                                  68020
 35                                  68032
 36                                  68020
 37                                  68010
 54                                  68032
 55                                  68028
 56                                  68026
 85                                  68046
 102                                 68040
 116                                 68006
 117                                 68010
 118                                 68008
 119                                 68006
 120                                 68014
 124                                 68020
 127                                 68028
 128                                 68036
 138                                 68012
 139                                 67980
 140                                 67960
 142                                 68012
 143                                 67922
 144                                 68040
 145                                 68040
 215                                 68036
 221                                 68032
 228                                 68030

      Homozygote Count European (non-Finnish)  \
 0                                          0
 1                                          0
 3                                          0
 29                                         0
 30                                         0
 31                                         0
 33                                         0
 34                                         0
 35                                         0
 36                                         0
 37                                         0
 54                                         0
 55                                         0
 56                                         0
 85                                         0
 102                                        0
 116                                        0
 117                                        0
 118                                        0
 119                                        0
 120                                        0
 124                                        0
 127                                        0
 128                                        0
 138                                        0
 139                                        0
 140                                        0
 142                                        0
 143                                        0
 144                                        0
 145                                        0
 215                                        0
 221                                        0
 228                                        0

      Hemizygote Count European (non-Finnish)  PTM  \
 0                                          0    s
 1                                          0    s
 3                                          0    s
 29                                         0    s
 30                                         0    s
 31                                         0    s
 33                                         0    s
 34                                         0    s
 35                                         0    s
 36                                         0    s
 37                                         0    s
 54                                         0    s
 55                                         0    s
 56                                         0    s
 85                                         0    s
 102                                        0    s
 116                                        0    s
 117                                        0    s
 118                                        0    s
 119                                        0    s
 120                                        0    s
 124                                        0    s
 127                                        0    s
 128                                        0    s
 138                                        0    s
 139                                        0    s
 140                                        0    s
 142                                        0    s
 143                                        0    s
 144                                        0    s
 145                                        0    s
 215                                        0    s
 221                                        0    s
 228                                        0    s

                                                PTM_INF  \
 0    [[[PHOSPHORYLATION, PSP, NM_000484, 761, 0]], ...
 1        [[[PHOSPHORYLATION, PSP, NM_000484, 761, 1]]]
 3    [[[UBIQUITINATION, PSP, NM_000484, 751, 1]], [...
 29   [[[SUMOYLATION, PSP, NM_000484, 670, 1]], [[SU...
 30   [[[O-GalNAc, PSP, NM_000484, 667, 1], [O-GLYCO...
 31   [[[O-GalNAc, PSP, NM_000484, 667, 1], [O-GLYCO...
 33   [[[O-GalNAc, PSP, NM_000484, 663, -1], [O-GLYC...
 34   [[[O-GalNAc, PSP, NM_000484, 663, 1], [O-GLYCO...
 35   [[[O-GalNAc, PSP, NM_000484, 659, -1], [O-GLYC...
 36   [[[O-GalNAc, PSP, NM_000484, 659, 1], [O-GLYCO...
 37   [[[O-GalNAc, PSP, NM_000484, 656, -1], [O-GLYC...
 54             [[[O-GalNAc, PSP, NM_000484, 600, -1]]]
 55             [[[O-GalNAc, PSP, NM_000484, 600, -1]]]
 56              [[[O-GalNAc, PSP, NM_000484, 600, 1]]]
 85      [[[N-GLYCOSYLATION, unip, NM_000484, 542, 1]]]
 102     [[[PHOSPHORYLATION, unip, NM_000484, 497, 1]]]
 116    [[[MONO-METHYLATION, PSP, NM_000484, 468, -1]]]
 117    [[[MONO-METHYLATION, PSP, NM_000484, 468, -1]]]
 118     [[[MONO-METHYLATION, PSP, NM_000484, 468, 0]]]
 119     [[[MONO-METHYLATION, PSP, NM_000484, 468, 0]]]
 120     [[[MONO-METHYLATION, PSP, NM_000484, 468, 1]]]
 124  [[[PHOSPHORYLATION, PSP, NM_000484, 441, -1], ...
 127       [[[UBIQUITINATION, PSP, NM_000484, 429, 0]]]
 128       [[[UBIQUITINATION, PSP, NM_000484, 429, 0]]]
 138  [[[PHOSPHORYLATION, PSP, NM_000484, 381, -1], ...
 139  [[[PHOSPHORYLATION, PSP, NM_000484, 381, 0], [...
 140  [[[PHOSPHORYLATION, PSP, NM_000484, 381, 1], [...
 142  [[[O-GalNAc, PSP, NM_000484, 370, 0]], [[PHOSP...
 143  [[[O-GalNAc, PSP, NM_000484, 366, 0]], [[O-Gal...
 144      [[[UBIQUITINATION, PSP, NM_000484, 363, -1]]]
 145      [[[UBIQUITINATION, PSP, NM_000484, 363, -1]]]
 215  [[[PHOSPHORYLATION, PSP, NM_000484, 206, 0], [...
 221  [[[PHOSPHORYLATION, PSP, NM_000484, 198, 0], [...
 228  [[[ACETYLATION, PSP, NM_000484, 178, 0], [UBIQ...

                                              Variantes
 0    [[NM_000484.4, 761], [NM_201414.3, 686], [NM_2...
 1    [[NM_000484.4, 760], [NM_201414.3, 685], [NM_2...
 3    [[NM_000484.4, 750], [NM_201414.3, 675], [NM_2...
 29   [[NM_000484.4, 669], [NM_201414.3, 594], [NM_2...
 30   [[NM_000484.4, 666], [NM_201414.3, 591], [NM_2...
 31   [[NM_000484.4, 666], [NM_201414.3, 591], [NM_2...
 33   [[NM_000484.4, 664], [NM_201414.3, 589], [NM_2...
 34   [[NM_000484.4, 662], [NM_201414.3, 587], [NM_2...
 35   [[NM_000484.4, 660], [NM_201414.3, 585], [NM_2...
 36   [[NM_000484.4, 658], [NM_201414.3, 583], [NM_2...
 37   [[NM_000484.4, 657], [NM_201414.3, 582], [NM_2...
 54   [[NM_000484.4, 601], [NM_201414.3, 526], [NM_2...
 55   [[NM_000484.4, 601], [NM_201414.3, 526], [NM_2...
 56   [[NM_000484.4, 599], [NM_201414.3, 524], [NM_2...
 85   [[NM_000484.4, 541], [NM_201414.3, 466], [NM_2...
 102  [[NM_000484.4, 496], [NM_201414.3, 421], [NM_2...
 116  [[NM_000484.4, 469], [NM_201414.3, 394], [NM_2...
 117  [[NM_000484.4, 469], [NM_201414.3, 394], [NM_2...
 118  [[NM_000484.4, 468], [NM_201414.3, 393], [NM_2...
 119  [[NM_000484.4, 468], [NM_201414.3, 393], [NM_2...
 120  [[NM_000484.4, 467], [NM_201414.3, 392], [NM_2...
 124  [[NM_000484.4, 442], [NM_201414.3, 367], [NM_2...
 127  [[NM_000484.4, 429], [NM_201414.3, 354], [NM_2...
 128  [[NM_000484.4, 429], [NM_201414.3, 354], [NM_2...
 138  [[NM_000484.4, 382], [NM_201414.3, 307], [NM_2...
 139  [[NM_000484.4, 381], [NM_201414.3, 306], [NM_2...
 140  [[NM_000484.4, 380], [NM_201414.3, 305], [NM_2...
 142  [[NM_000484.4, 370], [NM_201414.3, 295], [NM_2...
 143  [[NM_000484.4, 366], [NM_201414.3, 291], [NM_2...
 144  [[NM_000484.4, 364], [NM_001136130.3, 308], [N...
 145  [[NM_000484.4, 364], [NM_001136130.3, 308], [N...
 215  [[NM_000484.4, 206], [NM_201414.3, 206], [NM_2...
 221  [[NM_000484.4, 198], [NM_201414.3, 198], [NM_2...
 228  [[NM_000484.4, 178], [NM_201414.3, 178], [NM_2...

 [34 rows x 64 columns],
 'MAPT':      Chromosome  Position         rsIDs Reference Alternate          Source  \
 0            17  45962347   rs974837695         C         A  gnomAD Genomes
 1            17  45962348  rs1477365646         C         T  gnomAD Genomes
 6            17  45962387   rs144611688         C         T  gnomAD Genomes
 7            17  45962392   rs746904464         G         A  gnomAD Genomes
 8            17  45962393  rs1568240688         G         A  gnomAD Genomes

In [16]:
from google.colab import files
df_resul_gnomad.to_csv('df_resul_gnomad.csv') 
files.download('df_resul_gnomad.csv')

In [ ]:
variantes=pd.read_csv("/content/drive/MyDrive/Projeto/Projeto/sabe2.txt", sep='\t')
dic_re1={}
df_resul_Sabe=pd.DataFrame(columns=["Gene","Sabe Total","Sabe_ptm","Sabe_Porc"])

for chave in dic :
  gene=chave
  variantes1=variantes[variantes["Gene"]==gene]
  final=tab_final(gene)
  final
  list_x=variantes1["posi"].tolist()
  
  tk=[]
  tk1=[]
  tk2=[]
  for hgh in range(len(list_x)):
    print(hgh)  
    x=list_x[hgh]

    teste1=tab_teste1(final,x)
    teste1
    df=tab_exons_seq(teste1)
    lista=resul(teste1,df,x)

    a,b=sitios(lista,gene)
    tk+=[a]
    tk1+=[b]
    tk2+=[lista]
  print(tk)
  variantes1["PTM"]=tk
  variantes1["PTM_INF"]=tk1
  variantes1["Variantes"]=tk2
  variantes_sito=variantes1[variantes1["PTM"]=="s"]
  dic_re1[chave]=variantes_sito
  X=len(variantes1)
  X1=len(variantes_sito)
  X2=(X1*100)/X
  X,X1,X2
  lg=[chave,X,X1,X2]
  df_resul_Sabe.loc[len(df_resul_Sabe)] = lg

In [18]:
df_resul_Sabe

    Gene Sabe Total Sabe_ptm  Sabe_Porc
0    APP         11        1   9.090909
1   MAPT         31        6  19.354839
2  PSEN1          4        0   0.000000
3  PSEN2         11        0   0.000000
4  TREM2         16        1   6.250000

In [19]:
from google.colab import files
df_resul_Sabe.to_csv('df_resul_Sabe.csv') 
files.download('df_resul_Sabe.csv')

In [22]:
dic_re1

{'APP':       Chro      posi Ref Al            Conse_P Gene  \
 19398   21  25911855   C  T  nonsynonymous SNV  APP

                                               Transcrip.     avsnp147 FILTER  \
 19398  APP:NM_001136129:exon11:c.G1402A:p.E468K,APP:N...  rs140304729   PASS

       CEGH_Filter  HomozygousALT_count  Hemizygous_count  Allele_number  \
 19398         vSR                    0               0.0           2342

        Allele_ALT_count  Frequencies         Cohort PTM  \
 19398               2.0     0.000854  SABE-WGS-1171   s

                                       PTM_INF  \
 19398  [[[O-GalNAc, PSP, NM_000484, 600, 1]]]

                                                Variantes
 19398  [[NM_000484.4, 599], [NM_201414.3, 524], [NM_2...  ,
 'MAPT':        Chro      posi Ref Al            Conse_P  Gene  \
 160412   17  45983441   G  A  nonsynonymous SNV  MAPT
 160415   17  45983912   C  T  nonsynonymous SNV  MAPT
 160426   17  45971888   G  A  nonsynonymous SNV  MAPT
 160431   17  45996468   G  A  nonsynonymous SNV  MAPT
 160435   17  45991482   T  C  nonsynonymous SNV  MAPT
 160439   17  45996557   G  A  nonsynonymous SNV  MAPT

                                                Transcrip.      avsnp147  \
 160412  MAPT:NM_001123066:exon6:c.G637A:p.G213R,MAPT:N...    rs76375268
 160415  MAPT:NM_001123066:exon6:c.C1108T:p.R370W,MAPT:...    rs17651549
 160426  MAPT:NM_001123066:exon3:c.G163A:p.G55R,MAPT:NM...  rs1012826460
 160431  MAPT:NM_016834:exon6:c.G452A:p.R151H,MAPT:NM_0...   rs115492908
 160435  MAPT:NM_016834:exon5:c.T278C:p.I93T,MAPT:NM_01...   rs114635790
 160439  MAPT:NM_016834:exon6:c.G541A:p.A181T,MAPT:NM_0...    rs63750096

        FILTER CEGH_Filter  HomozygousALT_count  Hemizygous_count  \
 160412   PASS          SR                    0               0.0
 160415   PASS         vSR                   54               0.0
 160426   PASS         vSR                    0               0.0
 160431   PASS         vSR                    0               0.0
 160435   PASS         vSR                    0               0.0
 160439   PASS         vSR                    0               0.0

         Allele_number  Allele_ALT_count  Frequencies         Cohort PTM  \
 160412           2342              29.0     0.012383  SABE-WGS-1171   s
 160415           2342             468.0     0.199829  SABE-WGS-1171   s
 160426           2342               1.0     0.000427  SABE-WGS-1171   s
 160431           2342               1.0     0.000427  SABE-WGS-1171   s
 160435           2342               3.0     0.001281  SABE-WGS-1171   s
 160439           2342               3.0     0.001281  SABE-WGS-1171   s

                                                   PTM_INF  \
 160412  [[[PHOSPHORYLATION, PSP, NM_016835, 214, 1], [...
 160415  [[[PHOSPHORYLATION, PSP, NM_016835, 369, -1], ...
 160426  [[[PHOSPHORYLATION, PSP, NM_005910, 56, 1]], [...
 160431  [[[PHOSPHORYLATION, PSP, NM_005910, 208, -1], ...
 160435  [[[PHOSPHORYLATION, PSP, NM_005910, 149, -1]],...
 160439  [[[PHOSPHORYLATION, PSP, NM_005910, 238, -1], ...

                                                 Variantes
 160412        [[NM_016835.5, 213], [NM_001123066.4, 213]]
 160415        [[NM_016835.5, 370], [NM_001123066.4, 370]]
 160426  [[NM_005910.6, 55], [NM_016835.5, 55], [NM_001...
 160431  [[NM_005910.6, 209], [NM_016834.5, 151], [NM_0...
 160435  [[NM_005910.6, 150], [NM_016834.5, 92], [NM_01...
 160439  [[NM_005910.6, 239], [NM_016834.5, 181], [NM_0...  ,
 'PSEN1': Empty DataFrame
 Columns: [Chro, posi, Ref, Al, Conse_P, Gene, Transcrip., avsnp147, FILTER, CEGH_Filter, HomozygousALT_count, Hemizygous_count, Allele_number, Allele_ALT_count, Frequencies, Cohort, PTM, PTM_INF, Variantes]
 Index: [],
 'PSEN2': Empty DataFrame
 Columns: [Chro, posi, Ref, Al, Conse_P, Gene, Transcrip., avsnp147, FILTER, CEGH_Filter, HomozygousALT_count, Hemizygous_count, Allele_number, Allele_ALT_count, Frequencies, Cohort, PTM, PTM_INF, Variantes]
 Index: [],
 'TREM2':        Chro      posi Ref Al            Conse_P   Gene  \
 293760    6  41161395   C  T  nonsynonymous SNV  TREM2

                                                Transcrip.     avsnp147 FILTER  \
 293760  TREM2:NM_001271821:exon2:c.G259A:p.D87N,TREM2:...  rs142232675   PASS

        CEGH_Filter  HomozygousALT_count  Hemizygous_count  Allele_number  \
 293760         vSR                    0               0.0           2342

         Allele_ALT_count  Frequencies         Cohort PTM  \
 293760               5.0     0.002135  SABE-WGS-1171   s

                                              PTM_INF  \
 293760  [[[PHOSPHORYLATION, PSP, NM_018965, 88, 1]]]

                                         Variantes
 293760  [[NM_018965.4, 87], [NM_001271821.2, 87]]  }